### ISSUE TITLE
Little documentation

### ISSUE THREAD

**Issue by mewcrazy** [freanuperiaa/gmaps_scraper#5]
Hey,

I'd love to use your python app. Unfortunately I'm not really used to python projects. Could you give me a little hint how to use your scraper?

Dennis

**Comment by freanuperiaa** [comment]
Hi Dennis!

First of all, I'd like to say that I did this for work. It barely works,
but it gets the job done! I uploaded it on github for future reference, I
haven't thought of making it nice for other people to use. Sorry!

You can go to core/generic_google_scraper.py, and if you look at line 155,
you can change the params (particularly, the self.DRIVER_TITLE) to whatever
you're planning to scrape off google maps. After that, you can simply go to
your terminal and execute the command `python3 generic_google_scraper.py`
and Selenium will do its job. Please take note that Selenium is quite slow
compared to Scrapy or the vanilla Python Requests library, and that I
didn't opt for the Webdriver to be headless (making the driver headless
would make it faster, but I was thinking that this would take some time).

About the documentation, I'll be doing it soon when I'll have free time. If
it gets some attention from other users, I guess I'll be improving the code.

Thanks!
